name: Namar - Tavan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/yuzuhazime/iperius_win-10_github_rdp/-/raw/main/down.bat?ref_type=heads" -OutFile down.bat
          cmd /c down.bat

      - name: Setup RDP
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/yuzuhazime/iperius_win-10_github_rdp/-/raw/main/setup.py?ref_type=heads" -OutFile setup.py
          python setup.py

      - name: Connect to LiteManager
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/yuzuhazime/iperius_win-10_github_rdp/-/raw/main/show.bat?ref_type=heads" -OutFile show.bat
          cmd /c show.bat

      - name: Time Counter
        run: |
          # Блокировка завершения важных процессов
          powershell -Command "Stop-Process -Name AnyDesk -Force:$false"  # Пример блокировки AnyDesk
          powershell -Command "Stop-Process -Name LiteManager -Force:$false"  # Пример блокировки LiteManager
          
          # Ваш основной счетчик времени
          cmd /c loop.bat
