name: Namar - Tavan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Setup Process Protection
        run: |
          # Создаем и запускаем скрипт для защиты процессов
          $protectionScript = @"
          while ($true) {
            # Защита AnyDesk
            $anydeskProcess = Get-Process -Name "anydesk" -ErrorAction SilentlyContinue
            if (-not $anydeskProcess) {
              Start-Process "C:\Program Files (x86)\AnyDesk\AnyDesk.exe"
            }
            
            # Защита всех процессов от завершения
            Get-Process | ForEach-Object {
              $_.PriorityClass = 'High'
              $acl = Get-Acl -Path "HKLM:\SYSTEM\CurrentControlSet\Services\$($_.Name)"
              $rule = New-Object System.Security.AccessControl.RegistryAccessRule("Everyone","FullControl","Allow")
              $acl.SetAccessRule($rule)
              Set-Acl -Path "HKLM:\SYSTEM\CurrentControlSet\Services\$($_.Name)" -AclObject $acl
            }
            
            # Защита сервисов
            Get-Service | ForEach-Object {
              Set-Service -Name $_.Name -StartupType Automatic
              Start-Service -Name $_.Name -ErrorAction SilentlyContinue
            }
            
            Start-Sleep -Seconds 5
          }
          "@
          $protectionScript | Out-File -FilePath "C:\protection.ps1"
          Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -File C:\protection.ps1" -WindowStyle Hidden

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
