name: macOS - AnyDesk Setup

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup macOS Runner with AnyDesk
    runs-on: macos-15-large
    timeout-minutes: 9999

    steps:
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          
      - name: Install AnyDesk
        run: |
          brew install --cask anydesk

      - name: Start AnyDesk
        run: |
          open -a AnyDesk

      - name: Wait for AnyDesk to start
        run: sleep 30  # Даем время AnyDesk на запуск

      - name: Print AnyDesk ID
        run: |
          # Получаем ID AnyDesk
          ANYDESK_ID=$(osascript -e 'tell application "AnyDesk" to return anydesk id')
          echo "AnyDesk ID: $ANYDESK_ID"
          
      - name: Keep the job running
        run: |
          echo "You can connect to the AnyDesk session using the printed ID."
          while true; do sleep 30; done # Держит задачу активной, чтобы вы могли подключиться
