name: Namar - Tavan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          # Скачиваем down.bat, если файл не существует
          if (-not (Test-Path "down.bat")) {
            Invoke-WebRequest -Uri "https://gitlab.com/yuzuhazime/iperius_win-10_github_rdp/-/raw/main/down.bat?ref_type=heads" -OutFile "down.bat"
          }
          cmd /c down.bat

      - name: Setup Configuration
        run: |
          # Скачиваем setup.py, если файл не существует
          if (-not (Test-Path "setup.py")) {
            Invoke-WebRequest -Uri "https://gitlab.com/yuzuhazime/iperius_win-10_github_rdp/-/raw/main/setup.py?ref_type=heads" -OutFile "setup.py"
          }
          python setup.py

      - name: Protect Processes
        run: |
          # Защита процессов от завершения
          $protectedProcesses = @("AnyDesk.exe", "PowerShell.exe", "rdp.exe")
          while ($true) {
              foreach ($process in $protectedProcesses) {
                  if (-not (Get-Process -Name $process -ErrorAction SilentlyContinue)) {
                      Write-Host "Process $process was killed! Restarting..."
                      Start-Process $process
                  }
              }
              Start-Sleep -Seconds 5
          }

      - name: Connect to LiteManager
        run: |
          # Скачиваем show.bat, если файл не существует
          if (-not (Test-Path "show.bat")) {
            Invoke-WebRequest -Uri "https://gitlab.com/yuzuhazime/iperius_win-10_github_rdp/-/raw/main/show.bat?ref_type=heads" -OutFile "show.bat"
          }
          cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
