name: macos-setup

on:
  push:
    branches:
      - main

jobs:
  setup-runner:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Download AnyDesk
        run: curl -o anydesk.dmg -L "https://download.anydesk.com/anydesk.dmg"

      - name: Mount and Install AnyDesk
        run: |
          hdiutil attach anydesk.dmg
          sudo cp -R /Volumes/AnyDesk/AnyDesk.app /Applications/
          hdiutil detach /Volumes/AnyDesk

      - name: Get AnyDesk Logs and Configurations
        run: |
          echo "Список содержимого домашней директории AnyDesk для поиска возможных конфигурационных файлов:"
          ls -R "$HOME/Library/Application Support/AnyDesk"

      - name: Verify Installation
        run: ls /Applications

      - name: Keep the runner alive
        run: sleep 21600  # Sleep for 6 hours
