name: macos-setup

on:
  push:
    branches:
      - main

jobs:
  setup-runner:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Download AnyDesk
        run: curl -o anydesk.dmg -L "https://download.anydesk.com/anydesk.dmg"

      - name: Mount and Install AnyDesk
        run: |
          hdiutil attach anydesk.dmg
          sudo cp -R /Volumes/AnyDesk/AnyDesk.app /Applications/
          hdiutil detach /Volumes/AnyDesk

      - name: Run AnyDesk to Generate Config
        run: |
          open -a /Applications/AnyDesk.app
          sleep 10
          osascript -e 'tell application "AnyDesk" to quit'

      - name: Extract AnyDesk ID
        run: |
          ID_FILE="$HOME/Library/Application Support/AnyDesk/system.conf"
          if [ -f "$ID_FILE" ]; then
              ANYDESK_ID=$(grep "ad.anynet.id" "$ID_FILE" | awk '{print $3}')
              echo "AnyDesk ID: $ANYDESK_ID"
          else
              echo "Не удалось найти файл конфигурации с ID."
          fi

      - name: Verify Installation
        run: ls /Applications

      - name: Keep the runner alive
        run: sleep 21600  # Sleep for 6 hours
