name: macOS
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make setup.sh executable
      run: chmod +x setup.sh

    - name: Set up the environment
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        ./setup.sh "Alone215" "Alone215" "$NGROK_AUTH_TOKEN"

    - name: ngrok is now listening to VNC connections on...
      run: |
        curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'

    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v2
