name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Setup Process Protection
        run: |
          # Создаем и запускаем скрипт защиты процессов
          $protectionScript = @'
          while ($true) {
            # Защита AnyDesk
            $anydeskProcess = Get-Process -Name "anydesk" -ErrorAction SilentlyContinue
            if (-not $anydeskProcess) {
              Start-Process "C:\Program Files (x86)\AnyDesk\AnyDesk.exe"
            }
            
            # Защита всех процессов
            Get-Process | ForEach-Object {
              $_.PriorityClass = 'High'
              $_.ProcessorAffinity = 0xFFFF
            }
            
            # Защита служб
            Get-Service | Where-Object {$_.Status -eq 'Running'} | Set-Service -StartupType Automatic
            
            Start-Sleep -Seconds 5
          }
          '@
          $protectionScript | Out-File -FilePath "C:\protection.ps1"
          Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -File C:\protection.ps1" -WindowStyle Hidden

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
