name: macOS - AnyDesk Connection

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building on macOS...
    runs-on: macos-15-large
    timeout-minutes: 9999
    
    steps:
      - name: Install Homebrew and Essentials
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install anydesk
          brew install awscli
          brew install azure/bicep/bicep
          brew install mongodb/brew/mongodb-community

      - name: Start AnyDesk
        run: |
          anydesk --start-service

      - name: Display AnyDesk Address
        run: |
          anydesk --get-address

      - name: Time Counter (Keep Job Running)
        run: |
          while true; do sleep 60; done
