name: macos-setup

on:
  push:
    branches:
      - main

jobs:
  setup-runner:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Tap AnyDesk repository (if available)
        run: brew tap anydesk/tap

      - name: Install AnyDesk
        run: brew install anydesk

      - name: Run AnyDesk and fetch ID
        run: |
          open -a AnyDesk
          sleep 10
          anydesk --get-id > anydesk-id.txt
          cat anydesk-id.txt

      - name: Sleep for 6 hours
        run: sleep 21600
