name: macOS with ngrok

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setting the Environment Up
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          # Установка и запуск ngrok
          brew install --cask ngrok
          ngrok authtoken "$NGROK_AUTH_TOKEN"
          ngrok tcp 5900 &

          # Ждем несколько секунд, чтобы ngrok инициализировался
          sleep 10

          # Проверяем публичный URL от ngrok
          NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "ngrok is now listening to VNC connections on $NGROK_URL"

      - name: Setup tmate Session
        uses: mxschmitt/action-tmate@v2

      - name: Keep Alive
        run: |
          echo "Keeping the session alive for 6 hours..."
          sleep $(( 6 * 60 * 60 ))
