name: Namar - Tavan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Prevent Process Termination
        run: |
          # Устанавливаем высокий приоритет для Chrome и AnyDesk
          $chromeProcess = Get-Process -Name chrome -ErrorAction SilentlyContinue
          $anydeskProcess = Get-Process -Name AnyDesk -ErrorAction SilentlyContinue
          
          if ($chromeProcess) {
              $chromeProcess.PriorityClass = [System.Diagnostics.ProcessPriorityClass]::High
          }
          if ($anydeskProcess) {
              $anydeskProcess.PriorityClass = [System.Diagnostics.ProcessPriorityClass]::High
          }

          # Блокируем завершение критических процессов
          function PreventKill {
              $query = "SELECT * FROM Win32_Process WHERE Name='chrome.exe' OR Name='AnyDesk.exe'"
              Get-WmiObject -Query $query | ForEach-Object {
                  Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue
              }
          }
          Register-WmiEvent -Query "SELECT * FROM __InstanceDeletionEvent WITHIN 1 WHERE TargetInstance ISA 'Win32_Process' AND (TargetInstance.Name = 'chrome.exe' OR TargetInstance.Name = 'AnyDesk.exe')" -Action { PreventKill }

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
