name: macOS

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up environment
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          echo "Setting up environment..."
          source setup.sh "Alone215" "Alone215" "$NGROK_AUTH_TOKEN"
      
      - name: Start ngrok and expose VNC
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          echo "Starting ngrok..."
          ngrok authtoken $NGROK_AUTH_TOKEN
          ngrok tcp 5900 --log=stdout > /dev/null &

      - name: Display ngrok public URL
        run: |
          sleep 10 # Wait for ngrok to initialize
          echo "ngrok is now listening to VNC connections on:"
          curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
      
      - name: Set up tmate session
        uses: mxschmitt/action-tmate@v2
        with:
          timeout-minutes: 360 # Run tmate session for 6 hours

      - name: Keep alive
        run: |
          echo "Keeping the workflow running for 6 hours..."
          sleep $(( 6 * 60 * 60 ))
