name: macos-setup

on:
  push:
    branches:
      - main

jobs:
  setup-runner:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start SSH server
        run: |
          echo "Starting SSH server..."
          sudo systemsetup -setremotelogin on
          sudo mkdir -p /etc/ssh
          sudo touch /etc/ssh/sshd_config
          echo "Port 2222" | sudo tee -a /etc/ssh/sshd_config
          sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
          
      - name: Generate SSH Key
        run: |
          ssh-keygen -t rsa -b 2048 -f ~/macos_runner_key -N ""
          echo "SSH Public Key:"
          cat ~/macos_runner_key.pub
          echo "Add this public key to your authorized keys in target Windows machine or any other machine for access."

      - name: Keep the runner alive
        run: |
          echo "Runner is alive... SSH into it using private key"
          sleep 21600  # Sleep for 6 hours

      - name: Output SSH Connection Details
        run: echo "Connect with: ssh -i ~/macos_runner_key -p 2222 <username>@<runner-ip>"

      - name: Display IP Address
        run: |
          IP=$(ipconfig getifaddr en0)
          echo "Connect to this IP Address: $IP"
