name: macOS with ngrok

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ngrok and setup VNC
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          brew install --cask ngrok
          ngrok authtoken "$NGROK_AUTH_TOKEN"
          screen -d -m ngrok tcp 5900  # Запустить ngrok в фоне
          sleep 5                      # Ждем, пока ngrok запустится
          echo "Ngrok is listening on:"
          curl --silent http://127.0.0.1:4040/api/tunnels

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
        with:
          limit-access-to-actor: true  # Добавление опции ограничения доступа по актору

      - name: Keep session alive
        run: |
          echo "Session is kept alive for 6 hours"
          sleep $((6 * 60 * 60))
